FROM tailordev/pandas

RUN apt-get update && apt-get install sudo

RUN export uid=1001 gid=1001 && \
    mkdir -p /home/developer && \
    echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
    chmod 0440 /etc/sudoers.d/developer && \
    chown ${uid}:${gid} -R /home/developer

RUN sudo pip install --upgrade pip
RUN pip install matplotlib
RUN pip install seaborn

USER developer
ENV HOME /home/developer
CMD /usr/bin/python
